{% set version = '1.5-7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quadprog
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/quadprog_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quadprog/quadprog_{{ version }}.tar.gz
  sha256: 1af41e57df6f2d08ee8b72a1a5ada137beadb36c7ec9ab9bdb7c05226e8ae76d

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('quadprog')"           # [not win]
    - "\"%R%\" -e \"library('quadprog')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=quadprog
  license: GPL (>= 2)
  summary: This package contains routines and documentation for solving quadratic programming
    problems.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: quadprog
# Type: Package
# Title: Functions to Solve Quadratic Programming Problems
# Version: 1.5-7
# Date: 2019-05-05
# Author: S original by Berwin A. Turlach <Berwin.Turlach@gmail.com> R port by Andreas Weingessel <Andreas.Weingessel@ci.tuwien.ac.at>
# Maintainer: Berwin A. Turlach <Berwin.Turlach@gmail.com>
# Description: This package contains routines and documentation for solving quadratic programming problems.
# Depends: R (>= 3.1.0)
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2019-05-05 06:40:19 UTC; berwin
# Repository: CRAN
# Date/Publication: 2019-05-06 19:00:03 UTC
